services:
  postgres:
    image: postgres:15
    container_name: my_project_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1Kq84M(vO\52}
      POSTGRES_DB: ${POSTGRES_DB:-ally}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: my_project_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin_password}
    depends_on:
      - postgres

volumes:
  postgres_data:
